site_name: Shadergif Documentation
theme: readthedocs
pages:
- Home: 'index.md'
- Manual:
    - 'Uniforms': 'manual/uniforms.md'
    - 'Tips & Code Snippets': 'manual/tips-and-snippets.md'
- Techniques:
    - 'Two triangles': 'techniques/two-triangles.md' 
- Development:
    - 'Generating the documentation': 'doc/doc.md'
    - 'Server':
        - 'Running the server': 'server/Server.md'